config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: "account", controllers: {
      omniauth_callbacks: "auth/omniauth_callbacks"
  }
  get 'store/index', as: :store_index

  resources :line_items do
    member do
      patch :change_quantity
      post :change_quantity
    end
  end
  resources :carts

  resources :products

  resources :orders

  root to: 'store#index'
end

app/models/product.rb
class Product < ApplicationRecord
  # 验证
  validates :title,:description,presence: true
  validates :title,uniqueness: true
  validates :price,numericality:{ greater_than_or_equal_to: 0.01 }

  # 关联关系
  has_many :attachments,as: :attachmentable
  has_many :line_items

  # 回调
  after_save :clear_cache
  before_destroy :ensure_not_referenced_by_any_item

  def clear_cache
    $namespaced_redis.del "products"
  end

  private

  # 确保没有商品在引用此产品
  def ensure_not_referenced_by_any_item
    if line_items.present?
      errors.add(:base,'line item present')
      throw :abort
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :set_product, only: [:show, :edit, :update, :destroy]


  def index
    @products = Product.all
  end


  def show
  end


  def new
    @product = Product.new
  end


  def edit
  end

  def create
    @product = Product.new(product_params)
    if @product.save
       @product.attachments.create(file: params[:file]) if params[:file]
       redirect_to @product, notice: 'Product was successfully created.'
    else
       render :new
    end
  end

  def update
    @product.update(product_params)
    redirect_to @product, notice: 'Product was successfully updated.'
    @products = Product.all
    ActionCable.server.broadcast 'products',
                                 html: render_to_string('store/index',layout:false)

  end

  def destroy
    @product.destroy
    redirect_to products_url, notice: 'Product was successfully destroyed.'
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params[:product].permit!
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.slim
= simple_form_for @product, html: { multipart: true }, :html => { :class => 'inline_form' } do |f|
  = error_messages(f)
  = f.input :title
  = f.input :description
  = file_field_tag :file
  = f.input :price

  = f.button :submit, class: 'btn-primary'

app/views/products/edit.html.slim
h4.bg-info 编辑商品
= render "form"
  

app/views/products/index.html.slim
= link_to "新建", new_product_path,class: 'btn btn-default'
hr
.row.center-block
- @products.each do |product|
  .col-lg-4
    .thumbnail.product-iWrap
      =image_tag(product.attachments.first.file.url(:thumb),class: "img-responsive") if product.attachments.present?
      .caption
        h4.h4= product.title
        p.text-warning= truncate(strip_tags(product.description))
      .product-operate
        span= link_to "详情",product_path(product)
        span= link_to "编辑",product_path(product)
        span= link_to "删除", product,method: :delete,data:{confirm: '确定删除吗？'}

app/views/products/new.html.slim
h4.bg-info 新建商品
= render "form"

app/views/products/show.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @product.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @product.description %></dd>
  <dd><%= @product.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @product.price %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              products_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_product_path(@product), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              product_path(@product),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>